server.port: 8080
spring.application.name: gateway-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl.defaultZone: http://${DISCOVERY_URL}:${DISCOVERY_PORT}/eureka
    instance:
        hostname: localhost
        preferIpAddress: true

zuul:
    host:
        connect-timeout-millis: 5000000
        socket-timeout-millis: 5000000
    ignoredServices: '*'
    routes:
        player-team-service:
            path: /player-team/**
            serviceId: player-team-service
            stripPrefix: true
        transfer-service:
            path: /transfer/**
            serviceId: transfer-service
            stripPrefix: true